apiVersion: v1
kind: Service
metadata:
  name: cd-service
spec:
  type: LoadBalancer
  selector:
    app: notes
  ports:
  - protocol: TCP
    port: 8022
    targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-deployment
spec:
  selector:
    matchLabels:
      app: notes
  replicas: 3
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: cd
        image: cd-image
        env:
        - name: "PORT"
          value: "8022"