apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: ci-cd-test
description: main application pipeline
serialPipeline:
 stages:
 - targetId: test
   profiles: []
 - targetId: staging
   profiles: []
 - targetId: prod
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: test
description: test cluster
gke:
 cluster: projects/anjali-blog-test/locations/us-central1/clusters/test
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: staging
description: staging cluster
gke:
 cluster: projects/anjali-blog-test/locations/us-central1/clusters/staging
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: production cluster
requireApproval: true
gke:
 cluster: projects/anjali-blog-test/locations/us-central1/clusters/prod